universe = docker

docker_image = biobakery/metaphlan:4.0.2

executable = WGS_metaphlan4.sh
arguments = $(sample)

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 8) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/RSEM-1.3.1.tar.gz, \
                       PROG_instl/samtools_1.9.tar.gz, \
                       PROG_instl/bedtools2-2.28.0.tar.gz, \
                       PROG_instl/STAR-2.7.10b.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

log = WGS_metaphlan4/HMDP001.log
error = WGS_metaphlan4/HMDP001.error
output = WGS_metaphlan4/HMDP001.out

sample = HMDP001

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP002.log
error = WGS_metaphlan4/HMDP002.error
output = WGS_metaphlan4/HMDP002.out

sample = HMDP002

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP003.log
error = WGS_metaphlan4/HMDP003.error
output = WGS_metaphlan4/HMDP003.out

sample = HMDP003

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP004.log
error = WGS_metaphlan4/HMDP004.error
output = WGS_metaphlan4/HMDP004.out

sample = HMDP004

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP005.log
error = WGS_metaphlan4/HMDP005.error
output = WGS_metaphlan4/HMDP005.out

sample = HMDP005

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP006.log
error = WGS_metaphlan4/HMDP006.error
output = WGS_metaphlan4/HMDP006.out

sample = HMDP006

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP007.log
error = WGS_metaphlan4/HMDP007.error
output = WGS_metaphlan4/HMDP007.out

sample = HMDP007

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP008.log
error = WGS_metaphlan4/HMDP008.error
output = WGS_metaphlan4/HMDP008.out

sample = HMDP008

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP009.log
error = WGS_metaphlan4/HMDP009.error
output = WGS_metaphlan4/HMDP009.out

sample = HMDP009

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP010.log
error = WGS_metaphlan4/HMDP010.error
output = WGS_metaphlan4/HMDP010.out

sample = HMDP010

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP011.log
error = WGS_metaphlan4/HMDP011.error
output = WGS_metaphlan4/HMDP011.out

sample = HMDP011

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP012.log
error = WGS_metaphlan4/HMDP012.error
output = WGS_metaphlan4/HMDP012.out

sample = HMDP012

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP013.log
error = WGS_metaphlan4/HMDP013.error
output = WGS_metaphlan4/HMDP013.out

sample = HMDP013

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP014.log
error = WGS_metaphlan4/HMDP014.error
output = WGS_metaphlan4/HMDP014.out

sample = HMDP014

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP015.log
error = WGS_metaphlan4/HMDP015.error
output = WGS_metaphlan4/HMDP015.out

sample = HMDP015

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP016.log
error = WGS_metaphlan4/HMDP016.error
output = WGS_metaphlan4/HMDP016.out

sample = HMDP016

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP017.log
error = WGS_metaphlan4/HMDP017.error
output = WGS_metaphlan4/HMDP017.out

sample = HMDP017

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP018.log
error = WGS_metaphlan4/HMDP018.error
output = WGS_metaphlan4/HMDP018.out

sample = HMDP018

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP019.log
error = WGS_metaphlan4/HMDP019.error
output = WGS_metaphlan4/HMDP019.out

sample = HMDP019

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP020.log
error = WGS_metaphlan4/HMDP020.error
output = WGS_metaphlan4/HMDP020.out

sample = HMDP020

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP021.log
error = WGS_metaphlan4/HMDP021.error
output = WGS_metaphlan4/HMDP021.out

sample = HMDP021

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP022.log
error = WGS_metaphlan4/HMDP022.error
output = WGS_metaphlan4/HMDP022.out

sample = HMDP022

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP023.log
error = WGS_metaphlan4/HMDP023.error
output = WGS_metaphlan4/HMDP023.out

sample = HMDP023

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP024.log
error = WGS_metaphlan4/HMDP024.error
output = WGS_metaphlan4/HMDP024.out

sample = HMDP024

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP025.log
error = WGS_metaphlan4/HMDP025.error
output = WGS_metaphlan4/HMDP025.out

sample = HMDP025

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP026.log
error = WGS_metaphlan4/HMDP026.error
output = WGS_metaphlan4/HMDP026.out

sample = HMDP026

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP027.log
error = WGS_metaphlan4/HMDP027.error
output = WGS_metaphlan4/HMDP027.out

sample = HMDP027

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP028.log
error = WGS_metaphlan4/HMDP028.error
output = WGS_metaphlan4/HMDP028.out

sample = HMDP028

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP029.log
error = WGS_metaphlan4/HMDP029.error
output = WGS_metaphlan4/HMDP029.out

sample = HMDP029

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP030.log
error = WGS_metaphlan4/HMDP030.error
output = WGS_metaphlan4/HMDP030.out

sample = HMDP030

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP031.log
error = WGS_metaphlan4/HMDP031.error
output = WGS_metaphlan4/HMDP031.out

sample = HMDP031

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP032.log
error = WGS_metaphlan4/HMDP032.error
output = WGS_metaphlan4/HMDP032.out

sample = HMDP032

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP033.log
error = WGS_metaphlan4/HMDP033.error
output = WGS_metaphlan4/HMDP033.out

sample = HMDP033

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP034.log
error = WGS_metaphlan4/HMDP034.error
output = WGS_metaphlan4/HMDP034.out

sample = HMDP034

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP035.log
error = WGS_metaphlan4/HMDP035.error
output = WGS_metaphlan4/HMDP035.out

sample = HMDP035

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP036.log
error = WGS_metaphlan4/HMDP036.error
output = WGS_metaphlan4/HMDP036.out

sample = HMDP036

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP037.log
error = WGS_metaphlan4/HMDP037.error
output = WGS_metaphlan4/HMDP037.out

sample = HMDP037

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP038.log
error = WGS_metaphlan4/HMDP038.error
output = WGS_metaphlan4/HMDP038.out

sample = HMDP038

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP039.log
error = WGS_metaphlan4/HMDP039.error
output = WGS_metaphlan4/HMDP039.out

sample = HMDP039

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP040.log
error = WGS_metaphlan4/HMDP040.error
output = WGS_metaphlan4/HMDP040.out

sample = HMDP040

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP041.log
error = WGS_metaphlan4/HMDP041.error
output = WGS_metaphlan4/HMDP041.out

sample = HMDP041

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP042.log
error = WGS_metaphlan4/HMDP042.error
output = WGS_metaphlan4/HMDP042.out

sample = HMDP042

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP043.log
error = WGS_metaphlan4/HMDP043.error
output = WGS_metaphlan4/HMDP043.out

sample = HMDP043

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP044.log
error = WGS_metaphlan4/HMDP044.error
output = WGS_metaphlan4/HMDP044.out

sample = HMDP044

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP045.log
error = WGS_metaphlan4/HMDP045.error
output = WGS_metaphlan4/HMDP045.out

sample = HMDP045

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP046.log
error = WGS_metaphlan4/HMDP046.error
output = WGS_metaphlan4/HMDP046.out

sample = HMDP046

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP047.log
error = WGS_metaphlan4/HMDP047.error
output = WGS_metaphlan4/HMDP047.out

sample = HMDP047

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP048.log
error = WGS_metaphlan4/HMDP048.error
output = WGS_metaphlan4/HMDP048.out

sample = HMDP048

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP049.log
error = WGS_metaphlan4/HMDP049.error
output = WGS_metaphlan4/HMDP049.out

sample = HMDP049

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP050.log
error = WGS_metaphlan4/HMDP050.error
output = WGS_metaphlan4/HMDP050.out

sample = HMDP050

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP051.log
error = WGS_metaphlan4/HMDP051.error
output = WGS_metaphlan4/HMDP051.out

sample = HMDP051

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP052.log
error = WGS_metaphlan4/HMDP052.error
output = WGS_metaphlan4/HMDP052.out

sample = HMDP052

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP053.log
error = WGS_metaphlan4/HMDP053.error
output = WGS_metaphlan4/HMDP053.out

sample = HMDP053

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP054.log
error = WGS_metaphlan4/HMDP054.error
output = WGS_metaphlan4/HMDP054.out

sample = HMDP054

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP055.log
error = WGS_metaphlan4/HMDP055.error
output = WGS_metaphlan4/HMDP055.out

sample = HMDP055

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP056.log
error = WGS_metaphlan4/HMDP056.error
output = WGS_metaphlan4/HMDP056.out

sample = HMDP056

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP057.log
error = WGS_metaphlan4/HMDP057.error
output = WGS_metaphlan4/HMDP057.out

sample = HMDP057

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP058.log
error = WGS_metaphlan4/HMDP058.error
output = WGS_metaphlan4/HMDP058.out

sample = HMDP058

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP059.log
error = WGS_metaphlan4/HMDP059.error
output = WGS_metaphlan4/HMDP059.out

sample = HMDP059

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP060.log
error = WGS_metaphlan4/HMDP060.error
output = WGS_metaphlan4/HMDP060.out

sample = HMDP060

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP061.log
error = WGS_metaphlan4/HMDP061.error
output = WGS_metaphlan4/HMDP061.out

sample = HMDP061

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP062.log
error = WGS_metaphlan4/HMDP062.error
output = WGS_metaphlan4/HMDP062.out

sample = HMDP062

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP063.log
error = WGS_metaphlan4/HMDP063.error
output = WGS_metaphlan4/HMDP063.out

sample = HMDP063

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP064.log
error = WGS_metaphlan4/HMDP064.error
output = WGS_metaphlan4/HMDP064.out

sample = HMDP064

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP065.log
error = WGS_metaphlan4/HMDP065.error
output = WGS_metaphlan4/HMDP065.out

sample = HMDP065

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP066.log
error = WGS_metaphlan4/HMDP066.error
output = WGS_metaphlan4/HMDP066.out

sample = HMDP066

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP067.log
error = WGS_metaphlan4/HMDP067.error
output = WGS_metaphlan4/HMDP067.out

sample = HMDP067

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP068.log
error = WGS_metaphlan4/HMDP068.error
output = WGS_metaphlan4/HMDP068.out

sample = HMDP068

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP069.log
error = WGS_metaphlan4/HMDP069.error
output = WGS_metaphlan4/HMDP069.out

sample = HMDP069

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP070.log
error = WGS_metaphlan4/HMDP070.error
output = WGS_metaphlan4/HMDP070.out

sample = HMDP070

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP071.log
error = WGS_metaphlan4/HMDP071.error
output = WGS_metaphlan4/HMDP071.out

sample = HMDP071

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP072.log
error = WGS_metaphlan4/HMDP072.error
output = WGS_metaphlan4/HMDP072.out

sample = HMDP072

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP073.log
error = WGS_metaphlan4/HMDP073.error
output = WGS_metaphlan4/HMDP073.out

sample = HMDP073

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP074.log
error = WGS_metaphlan4/HMDP074.error
output = WGS_metaphlan4/HMDP074.out

sample = HMDP074

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP075.log
error = WGS_metaphlan4/HMDP075.error
output = WGS_metaphlan4/HMDP075.out

sample = HMDP075

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP076.log
error = WGS_metaphlan4/HMDP076.error
output = WGS_metaphlan4/HMDP076.out

sample = HMDP076

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP077.log
error = WGS_metaphlan4/HMDP077.error
output = WGS_metaphlan4/HMDP077.out

sample = HMDP077

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP078.log
error = WGS_metaphlan4/HMDP078.error
output = WGS_metaphlan4/HMDP078.out

sample = HMDP078

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP079.log
error = WGS_metaphlan4/HMDP079.error
output = WGS_metaphlan4/HMDP079.out

sample = HMDP079

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP080.log
error = WGS_metaphlan4/HMDP080.error
output = WGS_metaphlan4/HMDP080.out

sample = HMDP080

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP081.log
error = WGS_metaphlan4/HMDP081.error
output = WGS_metaphlan4/HMDP081.out

sample = HMDP081

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP082.log
error = WGS_metaphlan4/HMDP082.error
output = WGS_metaphlan4/HMDP082.out

sample = HMDP082

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP083.log
error = WGS_metaphlan4/HMDP083.error
output = WGS_metaphlan4/HMDP083.out

sample = HMDP083

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP084.log
error = WGS_metaphlan4/HMDP084.error
output = WGS_metaphlan4/HMDP084.out

sample = HMDP084

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP085.log
error = WGS_metaphlan4/HMDP085.error
output = WGS_metaphlan4/HMDP085.out

sample = HMDP085

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP086.log
error = WGS_metaphlan4/HMDP086.error
output = WGS_metaphlan4/HMDP086.out

sample = HMDP086

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP087.log
error = WGS_metaphlan4/HMDP087.error
output = WGS_metaphlan4/HMDP087.out

sample = HMDP087

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP088.log
error = WGS_metaphlan4/HMDP088.error
output = WGS_metaphlan4/HMDP088.out

sample = HMDP088

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP089.log
error = WGS_metaphlan4/HMDP089.error
output = WGS_metaphlan4/HMDP089.out

sample = HMDP089

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP090.log
error = WGS_metaphlan4/HMDP090.error
output = WGS_metaphlan4/HMDP090.out

sample = HMDP090

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP091.log
error = WGS_metaphlan4/HMDP091.error
output = WGS_metaphlan4/HMDP091.out

sample = HMDP091

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP092.log
error = WGS_metaphlan4/HMDP092.error
output = WGS_metaphlan4/HMDP092.out

sample = HMDP092

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP093.log
error = WGS_metaphlan4/HMDP093.error
output = WGS_metaphlan4/HMDP093.out

sample = HMDP093

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP094.log
error = WGS_metaphlan4/HMDP094.error
output = WGS_metaphlan4/HMDP094.out

sample = HMDP094

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP095.log
error = WGS_metaphlan4/HMDP095.error
output = WGS_metaphlan4/HMDP095.out

sample = HMDP095

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP096.log
error = WGS_metaphlan4/HMDP096.error
output = WGS_metaphlan4/HMDP096.out

sample = HMDP096

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP097.log
error = WGS_metaphlan4/HMDP097.error
output = WGS_metaphlan4/HMDP097.out

sample = HMDP097

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP098.log
error = WGS_metaphlan4/HMDP098.error
output = WGS_metaphlan4/HMDP098.out

sample = HMDP098

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP099.log
error = WGS_metaphlan4/HMDP099.error
output = WGS_metaphlan4/HMDP099.out

sample = HMDP099

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP100.log
error = WGS_metaphlan4/HMDP100.error
output = WGS_metaphlan4/HMDP100.out

sample = HMDP100

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP101.log
error = WGS_metaphlan4/HMDP101.error
output = WGS_metaphlan4/HMDP101.out

sample = HMDP101

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP102.log
error = WGS_metaphlan4/HMDP102.error
output = WGS_metaphlan4/HMDP102.out

sample = HMDP102

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP103.log
error = WGS_metaphlan4/HMDP103.error
output = WGS_metaphlan4/HMDP103.out

sample = HMDP103

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP104.log
error = WGS_metaphlan4/HMDP104.error
output = WGS_metaphlan4/HMDP104.out

sample = HMDP104

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP105.log
error = WGS_metaphlan4/HMDP105.error
output = WGS_metaphlan4/HMDP105.out

sample = HMDP105

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP106.log
error = WGS_metaphlan4/HMDP106.error
output = WGS_metaphlan4/HMDP106.out

sample = HMDP106

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP107.log
error = WGS_metaphlan4/HMDP107.error
output = WGS_metaphlan4/HMDP107.out

sample = HMDP107

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP108.log
error = WGS_metaphlan4/HMDP108.error
output = WGS_metaphlan4/HMDP108.out

sample = HMDP108

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP109.log
error = WGS_metaphlan4/HMDP109.error
output = WGS_metaphlan4/HMDP109.out

sample = HMDP109

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP110.log
error = WGS_metaphlan4/HMDP110.error
output = WGS_metaphlan4/HMDP110.out

sample = HMDP110

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP111.log
error = WGS_metaphlan4/HMDP111.error
output = WGS_metaphlan4/HMDP111.out

sample = HMDP111

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP112.log
error = WGS_metaphlan4/HMDP112.error
output = WGS_metaphlan4/HMDP112.out

sample = HMDP112

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP113.log
error = WGS_metaphlan4/HMDP113.error
output = WGS_metaphlan4/HMDP113.out

sample = HMDP113

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP114.log
error = WGS_metaphlan4/HMDP114.error
output = WGS_metaphlan4/HMDP114.out

sample = HMDP114

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP115.log
error = WGS_metaphlan4/HMDP115.error
output = WGS_metaphlan4/HMDP115.out

sample = HMDP115

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP116.log
error = WGS_metaphlan4/HMDP116.error
output = WGS_metaphlan4/HMDP116.out

sample = HMDP116

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP117.log
error = WGS_metaphlan4/HMDP117.error
output = WGS_metaphlan4/HMDP117.out

sample = HMDP117

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP118.log
error = WGS_metaphlan4/HMDP118.error
output = WGS_metaphlan4/HMDP118.out

sample = HMDP118

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP119.log
error = WGS_metaphlan4/HMDP119.error
output = WGS_metaphlan4/HMDP119.out

sample = HMDP119

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP120.log
error = WGS_metaphlan4/HMDP120.error
output = WGS_metaphlan4/HMDP120.out

sample = HMDP120

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP121.log
error = WGS_metaphlan4/HMDP121.error
output = WGS_metaphlan4/HMDP121.out

sample = HMDP121

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP122.log
error = WGS_metaphlan4/HMDP122.error
output = WGS_metaphlan4/HMDP122.out

sample = HMDP122

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP123.log
error = WGS_metaphlan4/HMDP123.error
output = WGS_metaphlan4/HMDP123.out

sample = HMDP123

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP124.log
error = WGS_metaphlan4/HMDP124.error
output = WGS_metaphlan4/HMDP124.out

sample = HMDP124

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP125.log
error = WGS_metaphlan4/HMDP125.error
output = WGS_metaphlan4/HMDP125.out

sample = HMDP125

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP126.log
error = WGS_metaphlan4/HMDP126.error
output = WGS_metaphlan4/HMDP126.out

sample = HMDP126

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP127.log
error = WGS_metaphlan4/HMDP127.error
output = WGS_metaphlan4/HMDP127.out

sample = HMDP127

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP128.log
error = WGS_metaphlan4/HMDP128.error
output = WGS_metaphlan4/HMDP128.out

sample = HMDP128

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP129.log
error = WGS_metaphlan4/HMDP129.error
output = WGS_metaphlan4/HMDP129.out

sample = HMDP129

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP130.log
error = WGS_metaphlan4/HMDP130.error
output = WGS_metaphlan4/HMDP130.out

sample = HMDP130

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP131.log
error = WGS_metaphlan4/HMDP131.error
output = WGS_metaphlan4/HMDP131.out

sample = HMDP131

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP132.log
error = WGS_metaphlan4/HMDP132.error
output = WGS_metaphlan4/HMDP132.out

sample = HMDP132

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP133.log
error = WGS_metaphlan4/HMDP133.error
output = WGS_metaphlan4/HMDP133.out

sample = HMDP133

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP134.log
error = WGS_metaphlan4/HMDP134.error
output = WGS_metaphlan4/HMDP134.out

sample = HMDP134

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP135.log
error = WGS_metaphlan4/HMDP135.error
output = WGS_metaphlan4/HMDP135.out

sample = HMDP135

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP136.log
error = WGS_metaphlan4/HMDP136.error
output = WGS_metaphlan4/HMDP136.out

sample = HMDP136

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP137.log
error = WGS_metaphlan4/HMDP137.error
output = WGS_metaphlan4/HMDP137.out

sample = HMDP137

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP138.log
error = WGS_metaphlan4/HMDP138.error
output = WGS_metaphlan4/HMDP138.out

sample = HMDP138

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP139.log
error = WGS_metaphlan4/HMDP139.error
output = WGS_metaphlan4/HMDP139.out

sample = HMDP139

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP140.log
error = WGS_metaphlan4/HMDP140.error
output = WGS_metaphlan4/HMDP140.out

sample = HMDP140

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP141.log
error = WGS_metaphlan4/HMDP141.error
output = WGS_metaphlan4/HMDP141.out

sample = HMDP141

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP142.log
error = WGS_metaphlan4/HMDP142.error
output = WGS_metaphlan4/HMDP142.out

sample = HMDP142

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP143.log
error = WGS_metaphlan4/HMDP143.error
output = WGS_metaphlan4/HMDP143.out

sample = HMDP143

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP144.log
error = WGS_metaphlan4/HMDP144.error
output = WGS_metaphlan4/HMDP144.out

sample = HMDP144

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP145.log
error = WGS_metaphlan4/HMDP145.error
output = WGS_metaphlan4/HMDP145.out

sample = HMDP145

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP146.log
error = WGS_metaphlan4/HMDP146.error
output = WGS_metaphlan4/HMDP146.out

sample = HMDP146

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP147.log
error = WGS_metaphlan4/HMDP147.error
output = WGS_metaphlan4/HMDP147.out

sample = HMDP147

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP148.log
error = WGS_metaphlan4/HMDP148.error
output = WGS_metaphlan4/HMDP148.out

sample = HMDP148

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP149.log
error = WGS_metaphlan4/HMDP149.error
output = WGS_metaphlan4/HMDP149.out

sample = HMDP149

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP150.log
error = WGS_metaphlan4/HMDP150.error
output = WGS_metaphlan4/HMDP150.out

sample = HMDP150

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP151.log
error = WGS_metaphlan4/HMDP151.error
output = WGS_metaphlan4/HMDP151.out

sample = HMDP151

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP152.log
error = WGS_metaphlan4/HMDP152.error
output = WGS_metaphlan4/HMDP152.out

sample = HMDP152

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP153.log
error = WGS_metaphlan4/HMDP153.error
output = WGS_metaphlan4/HMDP153.out

sample = HMDP153

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP154.log
error = WGS_metaphlan4/HMDP154.error
output = WGS_metaphlan4/HMDP154.out

sample = HMDP154

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP155.log
error = WGS_metaphlan4/HMDP155.error
output = WGS_metaphlan4/HMDP155.out

sample = HMDP155

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP156.log
error = WGS_metaphlan4/HMDP156.error
output = WGS_metaphlan4/HMDP156.out

sample = HMDP156

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP157.log
error = WGS_metaphlan4/HMDP157.error
output = WGS_metaphlan4/HMDP157.out

sample = HMDP157

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP158.log
error = WGS_metaphlan4/HMDP158.error
output = WGS_metaphlan4/HMDP158.out

sample = HMDP158

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP159.log
error = WGS_metaphlan4/HMDP159.error
output = WGS_metaphlan4/HMDP159.out

sample = HMDP159

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP160.log
error = WGS_metaphlan4/HMDP160.error
output = WGS_metaphlan4/HMDP160.out

sample = HMDP160

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP161.log
error = WGS_metaphlan4/HMDP161.error
output = WGS_metaphlan4/HMDP161.out

sample = HMDP161

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP162.log
error = WGS_metaphlan4/HMDP162.error
output = WGS_metaphlan4/HMDP162.out

sample = HMDP162

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP163.log
error = WGS_metaphlan4/HMDP163.error
output = WGS_metaphlan4/HMDP163.out

sample = HMDP163

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP164.log
error = WGS_metaphlan4/HMDP164.error
output = WGS_metaphlan4/HMDP164.out

sample = HMDP164

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP165.log
error = WGS_metaphlan4/HMDP165.error
output = WGS_metaphlan4/HMDP165.out

sample = HMDP165

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP166.log
error = WGS_metaphlan4/HMDP166.error
output = WGS_metaphlan4/HMDP166.out

sample = HMDP166

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP167.log
error = WGS_metaphlan4/HMDP167.error
output = WGS_metaphlan4/HMDP167.out

sample = HMDP167

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP168.log
error = WGS_metaphlan4/HMDP168.error
output = WGS_metaphlan4/HMDP168.out

sample = HMDP168

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP169.log
error = WGS_metaphlan4/HMDP169.error
output = WGS_metaphlan4/HMDP169.out

sample = HMDP169

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP170.log
error = WGS_metaphlan4/HMDP170.error
output = WGS_metaphlan4/HMDP170.out

sample = HMDP170

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP171.log
error = WGS_metaphlan4/HMDP171.error
output = WGS_metaphlan4/HMDP171.out

sample = HMDP171

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP172.log
error = WGS_metaphlan4/HMDP172.error
output = WGS_metaphlan4/HMDP172.out

sample = HMDP172

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP174.log
error = WGS_metaphlan4/HMDP174.error
output = WGS_metaphlan4/HMDP174.out

sample = HMDP174

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP175.log
error = WGS_metaphlan4/HMDP175.error
output = WGS_metaphlan4/HMDP175.out

sample = HMDP175

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP176.log
error = WGS_metaphlan4/HMDP176.error
output = WGS_metaphlan4/HMDP176.out

sample = HMDP176

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP177.log
error = WGS_metaphlan4/HMDP177.error
output = WGS_metaphlan4/HMDP177.out

sample = HMDP177

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP178.log
error = WGS_metaphlan4/HMDP178.error
output = WGS_metaphlan4/HMDP178.out

sample = HMDP178

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP179.log
error = WGS_metaphlan4/HMDP179.error
output = WGS_metaphlan4/HMDP179.out

sample = HMDP179

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP180.log
error = WGS_metaphlan4/HMDP180.error
output = WGS_metaphlan4/HMDP180.out

sample = HMDP180

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP181.log
error = WGS_metaphlan4/HMDP181.error
output = WGS_metaphlan4/HMDP181.out

sample = HMDP181

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP182.log
error = WGS_metaphlan4/HMDP182.error
output = WGS_metaphlan4/HMDP182.out

sample = HMDP182

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP183.log
error = WGS_metaphlan4/HMDP183.error
output = WGS_metaphlan4/HMDP183.out

sample = HMDP183

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP184.log
error = WGS_metaphlan4/HMDP184.error
output = WGS_metaphlan4/HMDP184.out

sample = HMDP184

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP185.log
error = WGS_metaphlan4/HMDP185.error
output = WGS_metaphlan4/HMDP185.out

sample = HMDP185

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP186.log
error = WGS_metaphlan4/HMDP186.error
output = WGS_metaphlan4/HMDP186.out

sample = HMDP186

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP187.log
error = WGS_metaphlan4/HMDP187.error
output = WGS_metaphlan4/HMDP187.out

sample = HMDP187

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP188.log
error = WGS_metaphlan4/HMDP188.error
output = WGS_metaphlan4/HMDP188.out

sample = HMDP188

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP189.log
error = WGS_metaphlan4/HMDP189.error
output = WGS_metaphlan4/HMDP189.out

sample = HMDP189

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP190.log
error = WGS_metaphlan4/HMDP190.error
output = WGS_metaphlan4/HMDP190.out

sample = HMDP190

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP191.log
error = WGS_metaphlan4/HMDP191.error
output = WGS_metaphlan4/HMDP191.out

sample = HMDP191

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP192.log
error = WGS_metaphlan4/HMDP192.error
output = WGS_metaphlan4/HMDP192.out

sample = HMDP192

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP193.log
error = WGS_metaphlan4/HMDP193.error
output = WGS_metaphlan4/HMDP193.out

sample = HMDP193

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP194.log
error = WGS_metaphlan4/HMDP194.error
output = WGS_metaphlan4/HMDP194.out

sample = HMDP194

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP195.log
error = WGS_metaphlan4/HMDP195.error
output = WGS_metaphlan4/HMDP195.out

sample = HMDP195

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP196.log
error = WGS_metaphlan4/HMDP196.error
output = WGS_metaphlan4/HMDP196.out

sample = HMDP196

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP197.log
error = WGS_metaphlan4/HMDP197.error
output = WGS_metaphlan4/HMDP197.out

sample = HMDP197

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP198.log
error = WGS_metaphlan4/HMDP198.error
output = WGS_metaphlan4/HMDP198.out

sample = HMDP198

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP199.log
error = WGS_metaphlan4/HMDP199.error
output = WGS_metaphlan4/HMDP199.out

sample = HMDP199

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP200.log
error = WGS_metaphlan4/HMDP200.error
output = WGS_metaphlan4/HMDP200.out

sample = HMDP200

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP201.log
error = WGS_metaphlan4/HMDP201.error
output = WGS_metaphlan4/HMDP201.out

sample = HMDP201

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP202.log
error = WGS_metaphlan4/HMDP202.error
output = WGS_metaphlan4/HMDP202.out

sample = HMDP202

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP203.log
error = WGS_metaphlan4/HMDP203.error
output = WGS_metaphlan4/HMDP203.out

sample = HMDP203

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP204.log
error = WGS_metaphlan4/HMDP204.error
output = WGS_metaphlan4/HMDP204.out

sample = HMDP204

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP205.log
error = WGS_metaphlan4/HMDP205.error
output = WGS_metaphlan4/HMDP205.out

sample = HMDP205

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP206.log
error = WGS_metaphlan4/HMDP206.error
output = WGS_metaphlan4/HMDP206.out

sample = HMDP206

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP207.log
error = WGS_metaphlan4/HMDP207.error
output = WGS_metaphlan4/HMDP207.out

sample = HMDP207

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP208.log
error = WGS_metaphlan4/HMDP208.error
output = WGS_metaphlan4/HMDP208.out

sample = HMDP208

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP209.log
error = WGS_metaphlan4/HMDP209.error
output = WGS_metaphlan4/HMDP209.out

sample = HMDP209

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP210.log
error = WGS_metaphlan4/HMDP210.error
output = WGS_metaphlan4/HMDP210.out

sample = HMDP210

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP211.log
error = WGS_metaphlan4/HMDP211.error
output = WGS_metaphlan4/HMDP211.out

sample = HMDP211

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP212.log
error = WGS_metaphlan4/HMDP212.error
output = WGS_metaphlan4/HMDP212.out

sample = HMDP212

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP213.log
error = WGS_metaphlan4/HMDP213.error
output = WGS_metaphlan4/HMDP213.out

sample = HMDP213

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP214.log
error = WGS_metaphlan4/HMDP214.error
output = WGS_metaphlan4/HMDP214.out

sample = HMDP214

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP215.log
error = WGS_metaphlan4/HMDP215.error
output = WGS_metaphlan4/HMDP215.out

sample = HMDP215

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP216.log
error = WGS_metaphlan4/HMDP216.error
output = WGS_metaphlan4/HMDP216.out

sample = HMDP216

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP217.log
error = WGS_metaphlan4/HMDP217.error
output = WGS_metaphlan4/HMDP217.out

sample = HMDP217

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP218.log
error = WGS_metaphlan4/HMDP218.error
output = WGS_metaphlan4/HMDP218.out

sample = HMDP218

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP219.log
error = WGS_metaphlan4/HMDP219.error
output = WGS_metaphlan4/HMDP219.out

sample = HMDP219

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP220.log
error = WGS_metaphlan4/HMDP220.error
output = WGS_metaphlan4/HMDP220.out

sample = HMDP220

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP221.log
error = WGS_metaphlan4/HMDP221.error
output = WGS_metaphlan4/HMDP221.out

sample = HMDP221

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP222.log
error = WGS_metaphlan4/HMDP222.error
output = WGS_metaphlan4/HMDP222.out

sample = HMDP222

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP223.log
error = WGS_metaphlan4/HMDP223.error
output = WGS_metaphlan4/HMDP223.out

sample = HMDP223

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP224.log
error = WGS_metaphlan4/HMDP224.error
output = WGS_metaphlan4/HMDP224.out

sample = HMDP224

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP225.log
error = WGS_metaphlan4/HMDP225.error
output = WGS_metaphlan4/HMDP225.out

sample = HMDP225

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP226.log
error = WGS_metaphlan4/HMDP226.error
output = WGS_metaphlan4/HMDP226.out

sample = HMDP226

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP227.log
error = WGS_metaphlan4/HMDP227.error
output = WGS_metaphlan4/HMDP227.out

sample = HMDP227

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP228.log
error = WGS_metaphlan4/HMDP228.error
output = WGS_metaphlan4/HMDP228.out

sample = HMDP228

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP229.log
error = WGS_metaphlan4/HMDP229.error
output = WGS_metaphlan4/HMDP229.out

sample = HMDP229

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP230.log
error = WGS_metaphlan4/HMDP230.error
output = WGS_metaphlan4/HMDP230.out

sample = HMDP230

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP231.log
error = WGS_metaphlan4/HMDP231.error
output = WGS_metaphlan4/HMDP231.out

sample = HMDP231

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP232.log
error = WGS_metaphlan4/HMDP232.error
output = WGS_metaphlan4/HMDP232.out

sample = HMDP232

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP233.log
error = WGS_metaphlan4/HMDP233.error
output = WGS_metaphlan4/HMDP233.out

sample = HMDP233

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP234.log
error = WGS_metaphlan4/HMDP234.error
output = WGS_metaphlan4/HMDP234.out

sample = HMDP234

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP235.log
error = WGS_metaphlan4/HMDP235.error
output = WGS_metaphlan4/HMDP235.out

sample = HMDP235

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP236.log
error = WGS_metaphlan4/HMDP236.error
output = WGS_metaphlan4/HMDP236.out

sample = HMDP236

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP237.log
error = WGS_metaphlan4/HMDP237.error
output = WGS_metaphlan4/HMDP237.out

sample = HMDP237

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP238.log
error = WGS_metaphlan4/HMDP238.error
output = WGS_metaphlan4/HMDP238.out

sample = HMDP238

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP239.log
error = WGS_metaphlan4/HMDP239.error
output = WGS_metaphlan4/HMDP239.out

sample = HMDP239

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP240.log
error = WGS_metaphlan4/HMDP240.error
output = WGS_metaphlan4/HMDP240.out

sample = HMDP240

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP241.log
error = WGS_metaphlan4/HMDP241.error
output = WGS_metaphlan4/HMDP241.out

sample = HMDP241

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP242.log
error = WGS_metaphlan4/HMDP242.error
output = WGS_metaphlan4/HMDP242.out

sample = HMDP242

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP243.log
error = WGS_metaphlan4/HMDP243.error
output = WGS_metaphlan4/HMDP243.out

sample = HMDP243

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP244.log
error = WGS_metaphlan4/HMDP244.error
output = WGS_metaphlan4/HMDP244.out

sample = HMDP244

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP245.log
error = WGS_metaphlan4/HMDP245.error
output = WGS_metaphlan4/HMDP245.out

sample = HMDP245

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP246.log
error = WGS_metaphlan4/HMDP246.error
output = WGS_metaphlan4/HMDP246.out

sample = HMDP246

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP247.log
error = WGS_metaphlan4/HMDP247.error
output = WGS_metaphlan4/HMDP247.out

sample = HMDP247

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP248.log
error = WGS_metaphlan4/HMDP248.error
output = WGS_metaphlan4/HMDP248.out

sample = HMDP248

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP249.log
error = WGS_metaphlan4/HMDP249.error
output = WGS_metaphlan4/HMDP249.out

sample = HMDP249

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP250.log
error = WGS_metaphlan4/HMDP250.error
output = WGS_metaphlan4/HMDP250.out

sample = HMDP250

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP251.log
error = WGS_metaphlan4/HMDP251.error
output = WGS_metaphlan4/HMDP251.out

sample = HMDP251

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP252.log
error = WGS_metaphlan4/HMDP252.error
output = WGS_metaphlan4/HMDP252.out

sample = HMDP252

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP253.log
error = WGS_metaphlan4/HMDP253.error
output = WGS_metaphlan4/HMDP253.out

sample = HMDP253

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP254.log
error = WGS_metaphlan4/HMDP254.error
output = WGS_metaphlan4/HMDP254.out

sample = HMDP254

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP255.log
error = WGS_metaphlan4/HMDP255.error
output = WGS_metaphlan4/HMDP255.out

sample = HMDP255

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP256.log
error = WGS_metaphlan4/HMDP256.error
output = WGS_metaphlan4/HMDP256.out

sample = HMDP256

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP257.log
error = WGS_metaphlan4/HMDP257.error
output = WGS_metaphlan4/HMDP257.out

sample = HMDP257

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP258.log
error = WGS_metaphlan4/HMDP258.error
output = WGS_metaphlan4/HMDP258.out

sample = HMDP258

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP259.log
error = WGS_metaphlan4/HMDP259.error
output = WGS_metaphlan4/HMDP259.out

sample = HMDP259

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP260.log
error = WGS_metaphlan4/HMDP260.error
output = WGS_metaphlan4/HMDP260.out

sample = HMDP260

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP261.log
error = WGS_metaphlan4/HMDP261.error
output = WGS_metaphlan4/HMDP261.out

sample = HMDP261

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP262.log
error = WGS_metaphlan4/HMDP262.error
output = WGS_metaphlan4/HMDP262.out

sample = HMDP262

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP263.log
error = WGS_metaphlan4/HMDP263.error
output = WGS_metaphlan4/HMDP263.out

sample = HMDP263

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP264.log
error = WGS_metaphlan4/HMDP264.error
output = WGS_metaphlan4/HMDP264.out

sample = HMDP264

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP265.log
error = WGS_metaphlan4/HMDP265.error
output = WGS_metaphlan4/HMDP265.out

sample = HMDP265

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP266.log
error = WGS_metaphlan4/HMDP266.error
output = WGS_metaphlan4/HMDP266.out

sample = HMDP266

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP267.log
error = WGS_metaphlan4/HMDP267.error
output = WGS_metaphlan4/HMDP267.out

sample = HMDP267

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP268.log
error = WGS_metaphlan4/HMDP268.error
output = WGS_metaphlan4/HMDP268.out

sample = HMDP268

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP269.log
error = WGS_metaphlan4/HMDP269.error
output = WGS_metaphlan4/HMDP269.out

sample = HMDP269

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP270.log
error = WGS_metaphlan4/HMDP270.error
output = WGS_metaphlan4/HMDP270.out

sample = HMDP270

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP271.log
error = WGS_metaphlan4/HMDP271.error
output = WGS_metaphlan4/HMDP271.out

sample = HMDP271

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP272.log
error = WGS_metaphlan4/HMDP272.error
output = WGS_metaphlan4/HMDP272.out

sample = HMDP272

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP273.log
error = WGS_metaphlan4/HMDP273.error
output = WGS_metaphlan4/HMDP273.out

sample = HMDP273

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP274.log
error = WGS_metaphlan4/HMDP274.error
output = WGS_metaphlan4/HMDP274.out

sample = HMDP274

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP275.log
error = WGS_metaphlan4/HMDP275.error
output = WGS_metaphlan4/HMDP275.out

sample = HMDP275

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP276.log
error = WGS_metaphlan4/HMDP276.error
output = WGS_metaphlan4/HMDP276.out

sample = HMDP276

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP277.log
error = WGS_metaphlan4/HMDP277.error
output = WGS_metaphlan4/HMDP277.out

sample = HMDP277

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP278.log
error = WGS_metaphlan4/HMDP278.error
output = WGS_metaphlan4/HMDP278.out

sample = HMDP278

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP279.log
error = WGS_metaphlan4/HMDP279.error
output = WGS_metaphlan4/HMDP279.out

sample = HMDP279

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP280.log
error = WGS_metaphlan4/HMDP280.error
output = WGS_metaphlan4/HMDP280.out

sample = HMDP280

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP281.log
error = WGS_metaphlan4/HMDP281.error
output = WGS_metaphlan4/HMDP281.out

sample = HMDP281

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP282.log
error = WGS_metaphlan4/HMDP282.error
output = WGS_metaphlan4/HMDP282.out

sample = HMDP282

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP283.log
error = WGS_metaphlan4/HMDP283.error
output = WGS_metaphlan4/HMDP283.out

sample = HMDP283

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP284.log
error = WGS_metaphlan4/HMDP284.error
output = WGS_metaphlan4/HMDP284.out

sample = HMDP284

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP285.log
error = WGS_metaphlan4/HMDP285.error
output = WGS_metaphlan4/HMDP285.out

sample = HMDP285

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP286.log
error = WGS_metaphlan4/HMDP286.error
output = WGS_metaphlan4/HMDP286.out

sample = HMDP286

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP287.log
error = WGS_metaphlan4/HMDP287.error
output = WGS_metaphlan4/HMDP287.out

sample = HMDP287

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP288.log
error = WGS_metaphlan4/HMDP288.error
output = WGS_metaphlan4/HMDP288.out

sample = HMDP288

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP289.log
error = WGS_metaphlan4/HMDP289.error
output = WGS_metaphlan4/HMDP289.out

sample = HMDP289

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP290.log
error = WGS_metaphlan4/HMDP290.error
output = WGS_metaphlan4/HMDP290.out

sample = HMDP290

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP291.log
error = WGS_metaphlan4/HMDP291.error
output = WGS_metaphlan4/HMDP291.out

sample = HMDP291

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP292.log
error = WGS_metaphlan4/HMDP292.error
output = WGS_metaphlan4/HMDP292.out

sample = HMDP292

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP293.log
error = WGS_metaphlan4/HMDP293.error
output = WGS_metaphlan4/HMDP293.out

sample = HMDP293

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP294.log
error = WGS_metaphlan4/HMDP294.error
output = WGS_metaphlan4/HMDP294.out

sample = HMDP294

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP295.log
error = WGS_metaphlan4/HMDP295.error
output = WGS_metaphlan4/HMDP295.out

sample = HMDP295

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP296.log
error = WGS_metaphlan4/HMDP296.error
output = WGS_metaphlan4/HMDP296.out

sample = HMDP296

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP297.log
error = WGS_metaphlan4/HMDP297.error
output = WGS_metaphlan4/HMDP297.out

sample = HMDP297

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/HMDP298.log
error = WGS_metaphlan4/HMDP298.error
output = WGS_metaphlan4/HMDP298.out

sample = HMDP298

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue

log = WGS_metaphlan4/AA-0151.log
error = WGS_metaphlan4/AA-0151.error
output = WGS_metaphlan4/AA-0151.out

sample = AA-0151

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0217.log
error = WGS_metaphlan4/AA-0217.error
output = WGS_metaphlan4/AA-0217.out

sample = AA-0217

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0218.log
error = WGS_metaphlan4/AA-0218.error
output = WGS_metaphlan4/AA-0218.out

sample = AA-0218

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0219.log
error = WGS_metaphlan4/AA-0219.error
output = WGS_metaphlan4/AA-0219.out

sample = AA-0219

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0292.log
error = WGS_metaphlan4/AA-0292.error
output = WGS_metaphlan4/AA-0292.out

sample = AA-0292

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0296.log
error = WGS_metaphlan4/AA-0296.error
output = WGS_metaphlan4/AA-0296.out

sample = AA-0296

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0348.log
error = WGS_metaphlan4/AA-0348.error
output = WGS_metaphlan4/AA-0348.out

sample = AA-0348

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0361.log
error = WGS_metaphlan4/AA-0361.error
output = WGS_metaphlan4/AA-0361.out

sample = AA-0361

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0367.log
error = WGS_metaphlan4/AA-0367.error
output = WGS_metaphlan4/AA-0367.out

sample = AA-0367

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0381.log
error = WGS_metaphlan4/AA-0381.error
output = WGS_metaphlan4/AA-0381.out

sample = AA-0381

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0415.log
error = WGS_metaphlan4/AA-0415.error
output = WGS_metaphlan4/AA-0415.out

sample = AA-0415

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0435.log
error = WGS_metaphlan4/AA-0435.error
output = WGS_metaphlan4/AA-0435.out

sample = AA-0435

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0512.log
error = WGS_metaphlan4/AA-0512.error
output = WGS_metaphlan4/AA-0512.out

sample = AA-0512

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0538.log
error = WGS_metaphlan4/AA-0538.error
output = WGS_metaphlan4/AA-0538.out

sample = AA-0538

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0583.log
error = WGS_metaphlan4/AA-0583.error
output = WGS_metaphlan4/AA-0583.out

sample = AA-0583

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0610.log
error = WGS_metaphlan4/AA-0610.error
output = WGS_metaphlan4/AA-0610.out

sample = AA-0610

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0615.log
error = WGS_metaphlan4/AA-0615.error
output = WGS_metaphlan4/AA-0615.out

sample = AA-0615

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0634.log
error = WGS_metaphlan4/AA-0634.error
output = WGS_metaphlan4/AA-0634.out

sample = AA-0634

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0640.log
error = WGS_metaphlan4/AA-0640.error
output = WGS_metaphlan4/AA-0640.out

sample = AA-0640

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0680.log
error = WGS_metaphlan4/AA-0680.error
output = WGS_metaphlan4/AA-0680.out

sample = AA-0680

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0681.log
error = WGS_metaphlan4/AA-0681.error
output = WGS_metaphlan4/AA-0681.out

sample = AA-0681

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0690.log
error = WGS_metaphlan4/AA-0690.error
output = WGS_metaphlan4/AA-0690.out

sample = AA-0690

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0724.log
error = WGS_metaphlan4/AA-0724.error
output = WGS_metaphlan4/AA-0724.out

sample = AA-0724

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0744.log
error = WGS_metaphlan4/AA-0744.error
output = WGS_metaphlan4/AA-0744.out

sample = AA-0744

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0753.log
error = WGS_metaphlan4/AA-0753.error
output = WGS_metaphlan4/AA-0753.out

sample = AA-0753

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0755.log
error = WGS_metaphlan4/AA-0755.error
output = WGS_metaphlan4/AA-0755.out

sample = AA-0755

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0780.log
error = WGS_metaphlan4/AA-0780.error
output = WGS_metaphlan4/AA-0780.out

sample = AA-0780

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0822.log
error = WGS_metaphlan4/AA-0822.error
output = WGS_metaphlan4/AA-0822.out

sample = AA-0822

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0826.log
error = WGS_metaphlan4/AA-0826.error
output = WGS_metaphlan4/AA-0826.out

sample = AA-0826

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0837.log
error = WGS_metaphlan4/AA-0837.error
output = WGS_metaphlan4/AA-0837.out

sample = AA-0837

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0838.log
error = WGS_metaphlan4/AA-0838.error
output = WGS_metaphlan4/AA-0838.out

sample = AA-0838

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0893.log
error = WGS_metaphlan4/AA-0893.error
output = WGS_metaphlan4/AA-0893.out

sample = AA-0893

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0909.log
error = WGS_metaphlan4/AA-0909.error
output = WGS_metaphlan4/AA-0909.out

sample = AA-0909

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0915.log
error = WGS_metaphlan4/AA-0915.error
output = WGS_metaphlan4/AA-0915.out

sample = AA-0915

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0919.log
error = WGS_metaphlan4/AA-0919.error
output = WGS_metaphlan4/AA-0919.out

sample = AA-0919

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0920.log
error = WGS_metaphlan4/AA-0920.error
output = WGS_metaphlan4/AA-0920.out

sample = AA-0920

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0952.log
error = WGS_metaphlan4/AA-0952.error
output = WGS_metaphlan4/AA-0952.out

sample = AA-0952

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0954.log
error = WGS_metaphlan4/AA-0954.error
output = WGS_metaphlan4/AA-0954.out

sample = AA-0954

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0983.log
error = WGS_metaphlan4/AA-0983.error
output = WGS_metaphlan4/AA-0983.out

sample = AA-0983

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0989.log
error = WGS_metaphlan4/AA-0989.error
output = WGS_metaphlan4/AA-0989.out

sample = AA-0989

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-0990.log
error = WGS_metaphlan4/AA-0990.error
output = WGS_metaphlan4/AA-0990.out

sample = AA-0990

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1051.log
error = WGS_metaphlan4/AA-1051.error
output = WGS_metaphlan4/AA-1051.out

sample = AA-1051

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1052.log
error = WGS_metaphlan4/AA-1052.error
output = WGS_metaphlan4/AA-1052.out

sample = AA-1052

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1105.log
error = WGS_metaphlan4/AA-1105.error
output = WGS_metaphlan4/AA-1105.out

sample = AA-1105

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1106.log
error = WGS_metaphlan4/AA-1106.error
output = WGS_metaphlan4/AA-1106.out

sample = AA-1106

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1297.log
error = WGS_metaphlan4/AA-1297.error
output = WGS_metaphlan4/AA-1297.out

sample = AA-1297

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1299.log
error = WGS_metaphlan4/AA-1299.error
output = WGS_metaphlan4/AA-1299.out

sample = AA-1299

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1310.log
error = WGS_metaphlan4/AA-1310.error
output = WGS_metaphlan4/AA-1310.out

sample = AA-1310

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1325.log
error = WGS_metaphlan4/AA-1325.error
output = WGS_metaphlan4/AA-1325.out

sample = AA-1325

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1406.log
error = WGS_metaphlan4/AA-1406.error
output = WGS_metaphlan4/AA-1406.out

sample = AA-1406

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1407.log
error = WGS_metaphlan4/AA-1407.error
output = WGS_metaphlan4/AA-1407.out

sample = AA-1407

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1499.log
error = WGS_metaphlan4/AA-1499.error
output = WGS_metaphlan4/AA-1499.out

sample = AA-1499

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1604.log
error = WGS_metaphlan4/AA-1604.error
output = WGS_metaphlan4/AA-1604.out

sample = AA-1604

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1612.log
error = WGS_metaphlan4/AA-1612.error
output = WGS_metaphlan4/AA-1612.out

sample = AA-1612

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1613.log
error = WGS_metaphlan4/AA-1613.error
output = WGS_metaphlan4/AA-1613.out

sample = AA-1613

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1630.log
error = WGS_metaphlan4/AA-1630.error
output = WGS_metaphlan4/AA-1630.out

sample = AA-1630

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1631.log
error = WGS_metaphlan4/AA-1631.error
output = WGS_metaphlan4/AA-1631.out

sample = AA-1631

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue


log = WGS_metaphlan4/AA-1679.log
error = WGS_metaphlan4/AA-1679.error
output = WGS_metaphlan4/AA-1679.out

sample = AA-1679

request_memory = 64GB
request_disk = 100GB
request_cpus = 2

queue
